name: GitHub Actions Demo
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-20.04
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - run: echo "🖥️ The workflow is now ready to test your code on the runner."
            - name: Check where we are...
              run: |
                echo Home: "${HOME}"
                echo CWD: "$(pwd)"
                ls . > cwd.txt
                ls ${{ github.workspace }} > workspace.txt
            - name: Check which commands are installed...
              run: |
                ls /bin > bin.txt
                ls /sbin || true > sbin.txt
                ls /usr/bin > usr-bin.txt
                ls /usr/sbin || true > usr-sbin.txt
                ls /usr/local/bin || true > usr-local-bin.txt
                ls /usr/local/sbin || true > user-local-sbin.txt
                ls ~/.local/bin || true > home-local-bin.txt
            - name: Check the PATH...
              run: |
                cat "${GITHUB_PATH}" > github-path.txt
                echo "${PATH}" > path.txt
            - name: Webi Installs and PATH Updates
              run: |
                curl -sS https://webinstall.dev/ | bash
                echo "${HOME}/.local/bin" >> $GITHUB_PATH
                curl -sS https://webinstall.dev/node@14 | bash
                echo "${HOME}/.local/opt/node/bin" >> $GITHUB_PATH
                curl -sS https://webinstall.dev/hugo | bash
            - name: Verify Webi Installs
              run: |
                node --version
                hugo version
            - name: Add changes, if any
              run: |
                if [[ $(git diff --stat) != '' ]]; then
                  git config --global user.name 'Github Actions'
                  git config --global user.email 'github-actions@users.noreply.github.com'
                  git add *.txt
                  git commit -m "update bins list" || true
                  git push
                fi
            - run: echo "🍏 This job's status is ${{ job.status }}."
